-- Popolamento della tabella "assets" per gli ambienti di DEV e di TEST
-- cfr. Triplette_REMEDY-asset_id_CRM_v02.xlsx

INSERT INTO "zammad"."assets"
(id, asset_type, name, created_at, updated_at)
VALUES
(1, 'sw', 'Il mio medico - Scelta e revoca rivolta al cittadino', NOW(), NOW()),
(2, 'sw', 'AUTOCERTIFICAZIONE ESENZIONE PER REDDITO CITTADINI', NOW(), NOW()),
(3, 'sw', 'GESTIONE VACCINAZIONI CITTADINO', NOW(), NOW()),
(4, 'sw', 'GESTIONE CONSENSI E PREFERENZE CITTADINI', NOW(), NOW()),
(5, 'sw', 'ROL per cittadino', NOW(), NOW()),
(6, 'sw', 'SERVIZI PER LA STAMPA DEL PROMEMORIA', NOW(), NOW()),
(7, 'sw', 'Deleghe Cittadini Adulti', NOW(), NOW()),
(8, 'sw', 'Dematerializzazione buoni pazienti celiaci', NOW(), NOW()),
(9, 'sw', 'Gestione appuntamenti screening tumori femminili (cittadini)', NOW(), NOW()),
(11, 'sw', 'FSE per cittadino', NOW(), NOW()),
(12, 'sw', 'La Mia Salute', NOW(), NOW()),
(13, 'sw', 'COVID SOL CITTADINO', NOW(), NOW()),
(14, 'sw', 'Pagamento ticket via web', NOW(), NOW()),
(15, 'sw', 'AUTOCERTIFICAZIONE ESENZIONE PER PATOLOGIA CITTADINI', NOW(), NOW()),
(16, 'sw', 'Trova un', NOW(), NOW()),
(17, 'sw', 'FSE - Taccuino per cittadino', NOW(), NOW()),
(18, 'sw', 'SOL ESTRATTO CONTO TICKET SANITARI', NOW(), NOW()),
(19, 'sw', 'FINDOM - GESTIONALE DOMANDA FINPIEMONTE', NOW(), NOW()),
(20, 'sw', 'FINDOM - GESTIONALE DOMANDA FINPIEMONTE - BANDI 2020', NOW(), NOW()),
(21, 'sw', 'FINDOM - GESTIONALE DOMANDA FINPIEMONTE - BANDI 2021', NOW(), NOW()),
(22, 'sw', 'FINDOM - GESTIONALE DOMANDA FINPIEMONTE - BANDI 2022', NOW(), NOW()),
(23, 'sw', 'FINDOM - GESTIONALE DOMANDA FINPIEMONTE - BANDI 2023', NOW(), NOW()),
(24, 'sw', 'FINDOM - GESTIONALE DOMANDA FINPIEMONTE - BANDI 2024', NOW(), NOW()),
(25, 'sw', 'FINDOM - GESTIONALE DOMANDA FINPIEMONTE - BANDO INNOMETRO', NOW(), NOW()),
(26, 'sw', 'FINDOM - GESTIONALE DOMANDA FINPIEMONTE - BANDI 2026', NOW(), NOW()),
(27, 'sw', 'FINDOM - Gestionale Domanda Finpiemonte - Bonus Turismo', NOW(), NOW()),
(28, 'sw', 'FINDOM - GESTIONALE DOMANDA FINPIEMONTE - BONUS APS', NOW(), NOW()),
(29, 'sw', 'FINDOM - GESTIONALE DOMANDA FINPIEMONTE - MEZZI INQUINANTI', NOW(), NOW()),
(30, 'sw', 'FINDOM - GESTIONALE DOMANDA FINPIEMONTE - BONUS CULTURA', NOW(), NOW()),
(31, 'sw', 'FINDOM - GESTIONALE DOMANDA BANDI A16', NOW(), NOW()),
(32, 'sw', 'FINDOM - GESTIONALE DOMANDA FINPIEMONTE - BONUS CULTURA', NOW(), NOW()),
(33, 'sw', 'FINDOM - GEST.DOMANDA FINPIEMONTE-MEZZI INQUINANTI PRIVATI', NOW(), NOW()),
(34, 'sw', 'FINDOM - GEST. DOM. FINPIEMONTE - LAVORATORI SVANTAGGIATI', NOW(), NOW()),
(35, 'sw', 'FINDOM - GESTIONALE DOMANDA FINPIEMONTE - RISTORO NEVE', NOW(), NOW()),
(36, 'sw', 'FINDOM - GESTIONALE DOMANDA FINPIEMONTE - BANDO SMARTWORKING', NOW(), NOW()),
(37, 'sw', 'FINDOM - GESTIONALE DOMANDA FINPIEMONTE - BANDO GEN.BIOMASSE', NOW(), NOW()),
(38, 'sw', 'FINDOM - GEST.DOM - TESTATE GIORNALISTICHE - A19', NOW(), NOW()),
(39, 'sw', 'FINDOM - GEST.DOM - BENI LIBRARI 2021', NOW(), NOW()),
(40, 'sw', 'FINDOM - GEST.DOM - PROMOZIONE EDITORIA 2021', NOW(), NOW()),
(41, 'sw', 'FINDOM - GEST.DOM - VOUCHER SALONE LIBRO 2021', NOW(), NOW()),
(42, 'sw', 'FINDOM - GEST.DOM. FINPIEMONTE - STRUTT. RICETTIVE PMI', NOW(), NOW()),
(43, 'sw', 'GEST.DOM – ATTIVITA''  CULTURALI 2021', NOW(), NOW()),
(44, 'sw', 'FINDOM - GESTIONALE DOMANDA FINPIEMONTE- SOSTEGNO FORMAZIONE', NOW(), NOW()),
(45, 'sw', 'FINDOM - GESTIONALE DOMANDA FINPIEMONTE - RISTORO NEVE-M.12', NOW(), NOW()),
(46, 'sw', 'FINDOM - GESTIONALE DOMANDA FINPIEMONTE - RISTORO NEVE 12-21', NOW(), NOW()),
(47, 'sw', 'FINDOM - Gestionale Domanda FESR', NOW(), NOW()),
(48, 'sw', 'FINDOM- GESTIONALE DOMANDA A21 SPORT', NOW(), NOW()),
(49, 'sw', 'Gestione e monitoraggio finanziamenti - Gestionale Finanziamenti Regione - FESR', NOW(), NOW())
